### ISSUE TITLE
Ability to enable/disable sharing providers

### ISSUE THREAD

**Issue by nodiscc** [alexisju/social#1]
Hi, thank you for writing this plugin; I plan to install it as part of my next Shaarli install. :clap: 

There's this one little annoyance: ideally it should allow users to select which sharing services they want enabled, without touching the code. (eg. only display the `twitter` and `email` sharing buttons: )

```
$GLOBALS['plugins']['SHARING_PROVIDERS'] = array('twitter', 'email');
```

It would allow extending the list of providers without cluttering the interface. Note for possible implementation: add an HTML class to each sharing link in `social.html` (`class="share-diaspora" class="share-twitter"`...), only display link if class matches one of the `SHARING_PROVIDERS` items.

Alternatively, if you added classes, each one could probably be hidden from Shaarli's `user.css` (`.sharing-linkedin { display: none }`)

Everything above is untested.

**Comment by alexisju** [comment]
Hello, thank you for your feedback. I'm totally agree with you.

Maybe it will be even better to code this plugin like https://github.com/ArthurHoaro/launch-plugin

But, in fact, i'm not very confortable with php, CSS trick will be easier for me.

However i don't have much time in next weeks... feel free to submit PR ;-)

**Comment by agentcobra** [comment]
I will work on it after PR #5

**Comment by nodiscc** [comment]
I don't use the plugin anymore
